services:
  db:
    image: postgres
    volumes:
      - $HOME/srv224/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - 5432:5432
    ports:
      - 5432:5432
    restart: always
  app:
    build: .
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=rps2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - 8080:8080
    ports:
      - 8080:8080
    depends_on:
      - db